# Generated by Django 5.1.3 on 2024-11-27 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='arrendador',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre2', models.CharField(blank=True, max_length=30)),
                ('apellido2', models.CharField(blank=True, max_length=30)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmobiliaria.direccion')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmobiliaria.tipousuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
