# Generated by Django 5.1.3 on 2024-12-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_remove_inmueble_arrendador_perfil_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='arrendatario',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='fecha',
        ),
    ]
