# Generated by Django 5.1.3 on 2024-12-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_remove_inmueble_arrendatario_remove_inmueble_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('landlord', 'Arrendador'), ('tenant', 'arrendatario')], default='arrendatario', max_length=10),
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
